export enum UPermissions {
    MAIN_USER_CREATE = 'MAINTENANCE.USER.CREATE',
    MAIN_APLICATION_CREATE = 'MAINTENANCE.APLICATION.CREATE',
    MAIN_APLICATION_EDIT = 'MAINTENANCE.APLICATION.EDIT',
    MAIN_APLICATION_DELETE = 'MAINTENANCE.APLICATION.DELETE',
}